version: '3.3'

services:
 ledder:
  stop_grace_period: 0s
  build:
   context: .

  ports:
   - 3000:3000
  environment:
   - NODE_ENV=production
  # volumes:
  #  - ./:/app
  # command: npm run debug
  #volumes:
   #- ./displayconf.js:/app/displayconf.js
   #- ./presets:/app/presets

# volumes:
#  mongodb:
#  mongodb_config:
