import PixelBox from "../../PixelBox.js"
import Scheduler from "../../Scheduler.js"
import ControlGroup from "../../ControlGroup.js"
import PixelList from "../../PixelList.js"
import FxMovie from "../../fx/FxMovie.js"
import FxRotate from "../../fx/FxRotate.js"
import Animator from "../../Animator.js"
import DrawAsciiArtColor from "../../draw/DrawAsciiArtColor.js"


export default class Dino extends Animator {
    static category = "Sprites"
    static title = "Dinosaur"
    static description = "Mozilla/Chrome style dinosaur sprite"

    async run(box: PixelBox, scheduler: Scheduler, controls: ControlGroup, x = 0, y = 0) {

        const frames = new PixelList()
        
        // Standing - 32x32 T-Rex with big head, small arms, strong legs
        frames.add(new DrawAsciiArtColor(x, y, `
        ................................
        ................................
        ..........gggggggg..............
        .........gggggggggg.............
        ........gggggggggggg............
        .......gggggwwggggggg...........
        ......ggggggwwgggggggg..........
        ......ggggggggggggggggg.........
        .....gggggggggggggggggg.........
        .....gggggggggggggggggg.........
        ....gggggggggggggggggg..........
        ....ggggggggggggggggg...........
        ....gggggggggggggggg............
        ....gggggg......................
        ....ggggg.......................
        ....ggggggggggggggg.............
        .....ggggggggggggggg............
        .....ggggggggggggggg............
        .....ggggggggggggggg............
        ......gggggggggggggg............
        ......gggggggggggggg............
        .......ggggggggggggg............
        .......ggggggggggggg............
        ........gggggggggggg............
        ........gggggggggggg............
        .........gggg..gggg.............
        .........gggg..gggg.............
        ........ggggg..ggggg............
        ........ggggg..ggggg............
        ........mmm....mmm..............
        ................................
        ................................
        `));

          frames.add(new DrawAsciiArtColor(x, y, `
        ................................
        ................................
        ..........gggggggg..............
        .........gggggggggg.............
        ........gggggggggggg............
        .......gggggwwggggggg...........
        ......ggggggwwgggggggg..........
        ......ggggggggggggggggg.........
        .....gggggggggggggggggg.........
        .....gggggggggggggggggg.........
        ....gggggggggggggggggg..........
        ....ggggggggggggggggg...........
        ....gggggggggggggggg............
        ....gggggg......................
        ....ggggg.......................
        ....ggggggggggggggg.............
        .....ggggggggggggggg............
        .....ggggggggggggggg............
        .....ggggggggggggggg............
        ......gggggggggggggg............
        ......gggggggggggggg............
        .......ggggggggggggg............
        .......ggggggggggggg............
        ........gggggggggggg............
        ........gggggggggggg............
        ........gggg..gggg..............
        ........gggg..gggg..............
        .......ggggg..ggggg.............
        .......ggggg..ggggg.............
        .......mmm....mmm...............
        ................................
        ................................
        `));
              
        frames.centerV(box)

        let dinoBox = new PixelBox(box)
        box.add(dinoBox)

        new FxMovie(scheduler, controls, 4, 0).run(frames, dinoBox)
        new FxRotate(scheduler, controls, 1).run(frames, dinoBox)
    }
}
