import SpriteAnimator from "./SpriteAnimator.js"
import type { SpriteState } from "./SpriteAnimator.js"

// Santa with sleigh - 5 animation frames
const santaSledFrames = [
    `
.wr................
..rrr..............
...rrrr............
...rwbw............
...rwwww...........
....ww5............
...rrrrrrrw........
yy.rrrrw...........
ryyrrrrrr..rr..5...
rrrrrrrrrrrr...5...
..5.......5...5....
55555555555555.....
`,
    `
.rr................
.wrrr..............
...rrrr............
...rwbw............
...rwwww...........
....ww5............
...rrrrrrrw........
yy.rrrrw...........
ryyrrrrrr..rr..5...
rrrrrrrrrrrr...5...
..5.......5...5....
55555555555555.....
`,
    `
.wr................
..rrr..............
...rrrr............
...rwbw............
...rwwww..w........
....ww5..r.........
...rrrrrr..........
yy.rrrrw...........
ryyrrrrrr..rr..5...
rrrrrrrrrrrr...5...
..5.......5...5....
55555555555555.....
`,
    `
.rr................
.wrrr..............
...rrrr............
...rwbw............
...rwwww...........
....ww5............
...rrrrrrrw........
yy.rrrrw...........
ryyrrrrrr..rr..5...
rrrrrrrrrrrr...5...
..5.......5...5....
55555555555555.....
`,
    `
.wr................
..rrr..............
...rrrr............
...rwbw............
...rwwww...........
....ww5............
...rrrrrrrw........
yy.rrrrw...........
ryyrrrrrr..rr..5...
rrrrrrrrrrrr...5...
..5.......5...5....
55555555555555.....
`
];

// Reindeer - 5 animation frames
const reindeerFrames = [
    `
...................
..........55.......
..........5........      
...........55......
............5......
.............mb....
.............mmmr..
...m........mm.....
..wwmmmmmmmmmm.....
...mmmmmmmmmmmm....
..m.m........m.m...
.m.m..........m.m..
.m.m...........m.m.
`,
    `
...................
..........55.......
..........5........      
...........55......
............5......
.............mb....
.............mmmr..
...m........mm.....
..wwmmmmmmmmmm.....
...mmmmmmmmmmmm....
..m.m........m.m...
..m.m........m.m...
..m.m.........m.m..
`,
    `
...................
..........55.......
..........5........      
...........55......
............5......
.............mb....
.............mmmr..
...m........mm.....
..wwmmmmmmmmmm.....
...mmmmmmmmmmmm....
..m.m.......m.m....
..m.m........m.m...
.m.m........m.m....
`,
    `
...................
..........55.......
..........5........      
...........55......
............5......
.............mb....
.............mmmr..
...m........mm.....
..wwmmmmmmmmmm.....
...mmmmmmmmmmmm....
..m.m........mmm...
...m.m.......mm....
..m.m..............
`,
    `
...................
..........55.......
..........5........      
...........55......
............5......
.............mb....
.............mmmr..
...m........mm.....
..wwmmmmmmmmmm.....
...mmmmmmmmmmmm....
..m.m........m.m...
.m.m..........m.m..
m.m................
`
];

// Placeholder for when no reindeer - simple lights
const noReindeerFrames = [
    `.y.`,
    `.w.`,
    `.c.`,
    `.b.`,
    `.y.`
];

export class SantaSledSprite extends SpriteAnimator {
    private frameIndex: number = 0;

    constructor(x: number, y: number, speedX: number = -0.3, speedY: number = 0) {
        const initialState: SpriteState = {
            x,
            y,
            velocityX: speedX,
            velocityY: speedY
        };

        super(santaSledFrames[0], initialState, {
            wrapAround: true,
            minX: 0,
            minY: 0
        });
    }

    update(frameNr: number, boxWidth: number, boxHeight: number) {
        // Animate through frames (every 8 frames)
        if (frameNr % 8 === 0) {
            this.frameIndex = (this.frameIndex + 1) % santaSledFrames.length;
            this.sprite = santaSledFrames[this.frameIndex];
            // Invalidate flipped sprite cache
            (this as any).flippedSprite = null;
        }

        super.update(frameNr, boxWidth, boxHeight);
    }
}

export class ReindeerSprite extends SpriteAnimator {
    private frameIndex: number = 0;

    constructor(x: number, y: number, speedX: number = -0.3, speedY: number = 0) {
        const initialState: SpriteState = {
            x,
            y,
            velocityX: speedX,
            velocityY: speedY
        };

        super(reindeerFrames[0], initialState, {
            wrapAround: true,
            minX: 0,
            minY: 0
        });
    }

    update(frameNr: number, boxWidth: number, boxHeight: number) {
        // Animate through frames (every 8 frames)
        if (frameNr % 8 === 0) {
            this.frameIndex = (this.frameIndex + 1) % reindeerFrames.length;
            this.sprite = reindeerFrames[this.frameIndex];
            // Invalidate flipped sprite cache
            (this as any).flippedSprite = null;
        }

        super.update(frameNr, boxWidth, boxHeight);
    }
}

export class NoReindeerSprite extends SpriteAnimator {
    private frameIndex: number = 0;

    constructor(x: number, y: number, speedX: number = -0.3, speedY: number = 0) {
        const initialState: SpriteState = {
            x,
            y,
            velocityX: speedX,
            velocityY: speedY
        };

        super(noReindeerFrames[0], initialState, {
            wrapAround: true,
            minX: 0,
            minY: 0
        });
    }

    update(frameNr: number, boxWidth: number, boxHeight: number) {
        // Animate through frames (every 8 frames)
        if (frameNr % 8 === 0) {
            this.frameIndex = (this.frameIndex + 1) % noReindeerFrames.length;
            this.sprite = noReindeerFrames[this.frameIndex];
            // Invalidate flipped sprite cache
            (this as any).flippedSprite = null;
        }

        super.update(frameNr, boxWidth, boxHeight);
    }
}

export const XmasSprites = {
    SantaSledSprite,
    ReindeerSprite,
    NoReindeerSprite
};
